
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE bike (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  manufacturer VARCHAR(255) NOT NULL
);

CREATE TABLE user_bike (
  user_id INTEGER NOT NULL,
  bike_id integer NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (bike_id) REFERENCES bike (id)
);

CREATE TABLE tag(
	id PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL
);

CREATE TABLE post_tag(
	p_id INTEGER NOT NULL,
	t_id INTEGER NOT NULL,
	FOREIGN KEY (p_id) REFERENCES post (id),
  	FOREIGN KEY (t_id) REFERENCES tag (id)
);
